spring.application.name=letter

# Render External Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d80kmof7f7vs73cvkmvg-a.oregon-postgres.render.com:5432/logfilm
spring.datasource.username=logfilm_user
spring.datasource.password=NnTZ8rWdUqkI6AYEn2ma35N3hVQmkahJ
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# TMDB API
tmdb.api.key=3e5f8889038ef562a05774fff558ba96
tmdb.api.url=https://api.themoviedb.org/3/movie/
tmdb.api.search-url=https://api.themoviedb.org/3/search/movie

# JWT Secret
jwt.secret=benimGizliJwtSifremLetterboxdKlonuIcinCokUzun12345